### ISSUE TITLE
Trying to use online examples.

### ISSUE THREAD

**Issue by niyuki** [battosai30/MCP3424#10]
I have been trying to build a voltage meter via Arduino and MCP3424 and I looked at this website https://wiki.dfrobot.com/MCP3424_18-Bit_ADC-4_Channel_with_Programmable_Gain_Amplifier__SKU_DFR0316_
which is including following code that is similar to your example One Shot, with your library:
<code> /* MCP 3424 version 1.2 example sketch OneShotConversion
 Written by B@tto
 Contact : batto@hotmail.fr

 In this example, one conversion per second is performed on channel 1 and 16 bits resolution.
 A new conversion has to be initiated by the user
 */

 #include <Wire.h>
 #include <MCP3424.h>

 MCP3424 MCP(0x68);   // Declaration of MCP3424 with Address of I2C

 long Voltage;

 void setup(){

   Serial.begin(9600);
   MCP.Configuration(1,16,0,1); // Channel 1, 16 bits resolution, one-shot mode, amplifier gain = 1

 }

 void loop(){

   MCP.NewConversion();    // New conversion is initiated

   Voltage=MCP.Measure();  // Measure, note that the library waits for a complete conversion

   Serial.print("Voltage = ");
   Serial.print(Voltage);
   Serial.println("uV");  // unit: microVolt

   delay (1000);

 }</code>
 
 and I guess it's a older version so I kinda tried to update it to this:
 
 <code>  /* MCP 3424 version 1.2 example sketch OneShotConversion
 Written by B@tto
 Contact : batto@hotmail.fr

 In this example, one conversion per second is performed on channel 1 and 16 bits resolution.
 A new conversion has to be initiated by the user
 */

 #include <Wire.h>
 #include <MCP342x.h>

 MCP342x MCP(0x68);   // Declaration of MCP3424 with Address of I2C

 long Voltage;

 void setup(){

   Serial.begin(9600);
     MCP.begin(0);

   MCP.setConfiguration(1,16,0,1); // Channel 1, 16 bits resolution, one-shot mode, amplifier gain = 1

 }

 void loop(){

   MCP.newConversion();    // New conversion is initiated

   Voltage=MCP.measure();  // Measure, note that the library waits for a complete conversion

   Serial.print("Voltage = ");
   Serial.print(Voltage);
   Serial.println("uV");  // unit: microVolt

   delay (1000);

 }</code>
 
 now it is uploading the script but it is not printing into the serial monitor something.. just empty
 
<img width="642" alt="image" src="https://user-images.githubusercontent.com/75905663/159858328-97baf833-72ad-4c22-84b1-10ea6a66d433.png">

**Comment by niyuki** [comment]
The errors first started with
MCP3424.h: No such file or directory
 so I changed it to MCP342x.h
 and then the later updates like Configuration to setConfiguration
 or MCP.Measure() to MCP.measure()
 that is how I came on the last version above

**Comment by battosai30** [comment]
Hi, simply take the last version on this github ;) 1.2 is a very old one

**Comment by niyuki** [comment]
I mean I downloaded the version which is here but still don't know further

**Comment by battosai30** [comment]
https://github.com/battosai30/MCP3424/releases

**Comment by niyuki** [comment]
Okay I downloaded the v1.9 zip file and put the folder inside the libraries folder in arduino.
When I try to upload script it drops some warnings and is "Done Uploading" but still nothing is getting printed, even if there is nothing it should print 0 or not?
The "warnings":

In file included from \Arduino\libraries\MCP3424-master\MCP342x.h:35:0,
                 from \Arduino\libraries\MCP3424-master\MCP342x.cpp:25:
\ArduinoData\packages\arduino\hardware\avr\1.8.5\libraries\Wire\src/Wire.h: In member function 'uint8_t MCP342x::getConfiguration()':
\ArduinoData\packages\arduino\hardware\avr\1.8.5\libraries\Wire\src/Wire.h:68:13: note: candidate 1: uint8_t TwoWire::requestFrom(int, int)
     uint8_t requestFrom(int, int);
             ^~~~~~~~~~~
\ArduinoData\packages\arduino\hardware\avr\1.8.5\libraries\Wire\src/Wire.h:65:13: note: candidate 2: uint8_t TwoWire::requestFrom(uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t);
             ^~~~~~~~~~~

Am I doing something wrong?

**Comment by battosai30** [comment]
Yess it should.

What's your hardware ?
Try to add some Serial.print() like this to check if it's stuck somewhere : 

```
Serial.begin(9600); 
Serial.println("Hello");
delay(100);
MCP.begin(0);
Serial.println("begin() OK");
delay(100);
MCP.setConfiguration(1,16,0,1); // Channel 1, 16 bits resolution, one-shot mode, amplifier gain = 1
Serial.println("Config OK");
delay(100);
```

**Comment by niyuki** [comment]
Hardware is Arduino mega 2560 and mcp3434 
Ight it went great till the config part:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/75905663/160108304-31c9223e-df0e-475d-9da3-30df65405d09.png">

**Comment by battosai30** [comment]
Ok this kind of problem is usually linked to i2c transmission issue as when setconfiguration() is called, it will start an i2c transaction, and if something goes wrong (main reason is bad wiring) it's halted.

Can you post a picture of your wiring ?

**Comment by niyuki** [comment]
Sure, is this clear enough. I'm working just with this parts right now. I have on the left which is not on picture a wheatstone bridge and a 7 segment display. I'm just trying currently to create communication between mcp3424 and arduino mega 2560 ![WIN_20220325_12_47_21_Pro](https://user-images.githubusercontent.com/75905663/160115419-035f4305-3d1f-4484-ba8c-b3356081b866.jpg)

**Comment by niyuki** [comment]
Here is one from top view
![WIN_20220325_12_53_22_Pro](https://user-images.githubusercontent.com/75905663/160116156-822e2c46-c0a7-41e2-9b4e-88e60751c16c.jpg)

**Comment by battosai30** [comment]
The mcp is not powered :s

**Comment by niyuki** [comment]
Wait how isn't it? What did I forget

**Comment by battosai30** [comment]
Nothing is wired : 

![image](https://user-images.githubusercontent.com/5184702/160127731-e55de2dd-5d0c-45d4-b903-0ff7b3c311a7.png)

**Comment by niyuki** [comment]
Ohhh okay so I tried now to power by plugging like this or switching plugs but it still can't pass to config ok. Did I plug wrong?
<img width="196" alt="image" src="https://user-images.githubusercontent.com/75905663/160132575-3a594c13-7357-4b6a-8a8b-fd61bc61f231.png">

**Comment by battosai30** [comment]
"switching plugs ?" => you mean you tried to invert + and - ???! If yes, your MCP is very probably burnt ...
If no wiring seems good on picture but i2c adress pins are tied to low by default, so you should use : 

`MCP3424 MCP(0); `

instead of 

`MCP3424 MCP(0x68); `

**Comment by niyuki** [comment]
So like I connected in the drawing is wrong I guess? Just curious so I won't burn again or another MCP..

**Comment by battosai30** [comment]
On the picture it seems okay : you need to have MCP GND -> GND of Arduino and MCP VCC -> 5V of the Arduino.

Fo your record : just remember that semiconductors hates to be exposed to inverted voltage. it's very rare that a chip has internal protection against this. So "I wire and I will see what happens" is a very bad method in electronic xD

**Comment by niyuki** [comment]
Should I try it with the second MCP now with this order
![WIN_20220325_17_06_57_Pro](https://user-images.githubusercontent.com/75905663/160158237-93804c8a-3031-41bb-946b-91e6aaf21aab.jpg)

**Comment by battosai30** [comment]
It seems ok. Try like this, if it does not work, switch with a new MCP.
And for now, you should not connect something on any channel, we will discuss about this point after xD (one step at a time !)

**Comment by niyuki** [comment]
Ok do you have time or can I contact you somewhere else?

**Comment by battosai30** [comment]
Here it's ok, it adds some informations on this project ;)

**Comment by niyuki** [comment]
Tried on both MCPs and still doesnt show config ok
Are u available for a call, ig thats more healthy. I'm double checking though

**Comment by battosai30** [comment]
I think I would not tell you than we are discussing here xD it's so simple that I guess an obvious point is missed, so we just need to test obvious things :)

Try an i2c scan => https://playground.arduino.cc/Main/I2cScanner/ 

We will see if something is answering (it could be simple adress error)

Do you have a voltmeter ? Just check that mcp is well supllied and if i2c lines are 5V too.

**Comment by niyuki** [comment]
Well it keeps printing
Scanning...
No I2C devices found
and I'm just getting more confused about this though.
I don't have a voltmeter but at school. But I got covid so I'm unable for a few days to visit school.

**Comment by niyuki** [comment]
Uhm I got some nice news... I just found out that I plugged the SCL and SDA inverted so I corrected it and i2c scanner worked it is telling 0x68:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/75905663/160280639-92dc58f9-0945-4916-9d34-b7000b565e8d.png">

but it is still hanging on at there 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/75905663/160280716-9297cde1-a22c-434f-82c6-304d03f21a8a.png">

**Comment by battosai30** [comment]
It's strange : 0x68 is the expected address for MCP(0)

Try MCP(0x68) in case of bug

**Comment by niyuki** [comment]
MCP(0) and MCP(0x68) both doesnt get to config ok it gets stuck somehow
<img width="956" alt="image" src="https://user-images.githubusercontent.com/75905663/160549091-d9d5ad11-d3a6-4eb3-8245-aa99ab621b94.png">

**Comment by niyuki** [comment]
MCP(0x68) or (0) both dont go to config ok it gets stuck somehow
<img width="949" alt="image" src="https://user-images.githubusercontent.com/75905663/160549442-256d2fa4-8ebf-4efa-9259-b1a36c83082a.png">

**Comment by battosai30** [comment]
The "wiring" story is very strange : on first photo it's clearly good, you inverted them after ?

**Comment by niyuki** [comment]
I don't think so. Look
![WIN_20220329_11_14_23_Pro](https://user-images.githubusercontent.com/75905663/160577814-a1aca053-0e2d-45fa-aeac-13aab484dfb2.jpg)

**Comment by battosai30** [comment]
Yes it seems ok. And with this exact wiring, i2c scan gives you 0x68 ?

**Comment by niyuki** [comment]
Uhm well, somehow currently it runs but doesnt say either found or not found. See:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/75905663/160590185-4c736f7a-988e-40dc-9519-d79246ae6d13.png">
I pressed the reset button in the morning. May the reason be this?
Oh nvm, I just tried the other MCP and came back.
<img width="250" alt="image" src="https://user-images.githubusercontent.com/75905663/160592685-ac9297fd-ed70-4228-bff1-e5fc5bf2341b.png">
But still no "config ok"

**Comment by battosai30** [comment]
And you tried on adress 0 and 0x68 ?

**Comment by niyuki** [comment]
Yes both give same results

**Comment by niyuki** [comment]
Any options, ideas or what should I do now? I'm just getting more confused

**Comment by battosai30** [comment]
I made a new release, install it :  https://github.com/battosai30/MCP3424/releases/tag/v1.91

Try this code and telle me the result : 

```

#include <MCP342x.h>
#include <Wire.h>

MCP342x MCP(0); 

void setup() {

Serial.begin(9600); 
Serial.println("Hello");
delay(100);
MCP.begin(0);
Serial.println("begin() OK");
delay(100);
Serial.print("Adress = 0x");
Serial.println(MCP.getAddress(),HEX);
MCP.setConfiguration(1,16,0,1); 
Serial.println("Config OK");
delay(100);

}

void loop() {}
```

**Comment by niyuki** [comment]
It's showing this(kinda weird that it doesnt display completely "Adress = 0x"): 
<img width="934" alt="image" src="https://user-images.githubusercontent.com/75905663/161392861-bdbd707e-8d25-4cb8-b367-8a45b1cf2d44.png">

**Comment by battosai30** [comment]
Ok something is wrong : add delay(100) before setConfiguration()

**Comment by niyuki** [comment]
yep going to 0x68
<img width="931" alt="image" src="https://user-images.githubusercontent.com/75905663/161620978-31952dad-1f3a-4674-ae48-6185dea4f277.png">

**Comment by battosai30** [comment]
Ok ... Let's try this code : 

```
#include <Wire.h>

void setup() {

Serial.begin(9600);

Serial.println("Hello");
delay(100);
Wire.begin()
Serial.println("begin() OK");
delay(100);

Wire.beginTransmission(0x68);
Wire.write(0x28);
Wire.endTransmission();

Serial.println("Config OK");
delay(100);

}

void loop(){}
```

**Comment by niyuki** [comment]
Looks good I guess
<img width="399" alt="image" src="https://user-images.githubusercontent.com/75905663/161747829-4b8aab3d-0e16-48d1-87a1-5104857efeaa.png">

**Comment by battosai30** [comment]
Whhhhhaaaatttt !! It's driving me nuts xD

Try this : 

```
#include <Wire.h>

void setup() {

Serial.begin(9600);

Serial.println("Hello");
delay(100);
Wire.begin()
Serial.println("begin() OK");
delay(100);

MCP.setConfiguration(1,16,0,1); 

Serial.println("Config OK");
delay(100);

}

void loop(){}

setConfiguration(byte channel,uint8_t resolution,uint8_t mode,uint8_t pga)
{

uint8_t cfgbyte=0;
 
//int _resolution=resolution;
//_PGA=pga;
//uint32_t divisor = 1;
//_LSB = 2048000000/(divisor<<(resolutionConvert[_resolution]-1));

cfgbyte |= (channel & 0x3) << 5;
cfgbyte |= (mode & 0x1) << 4;
cfgbyte |= (resolution & 0x3) << 2;
cfgbyte |= pga & 0x3;

Wire.beginTransmission(0x68);
Wire.write(cfgbyte);
Wire.endTransmission();

}
```

**Comment by niyuki** [comment]
Did you forget to set MCP at the beginning bc it is saying 'MCP' was not declared in this scope

**Comment by battosai30** [comment]
I'm not using the library right now. 

I forgot a ; after Wire.begin()

**Comment by niyuki** [comment]
Yea already solved that but still can't run it clearly. Also tried to place the function above but this won't run so I placed it back. Currently it is:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/75905663/161840826-ca0db5a8-d6fe-4473-a952-c79276cc5d9f.png">

**Comment by battosai30** [comment]
I forgot a "void" before setConfiguration(byte channel,uint8_t resolution,uint8_t mode,uint8_t pga)

**Comment by niyuki** [comment]
Okay it worked 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/75905663/161952145-258b3878-fd5d-4dd2-9d26-e63bebd7fc67.png">

**Comment by battosai30** [comment]
Oh god, I have an idea : test the multichannel example https://github.com/battosai30/MCP3424/blob/master/Examples/MCP3424_Multichannel/MCP3424_Multichannel.ino

**Comment by niyuki** [comment]
Do I have to wire any cables to the other channels(currently only CH1 + and - to nothing)? This is resulting printing different values each time for same res(bits)
<img width="547" alt="image" src="https://user-images.githubusercontent.com/75905663/161964905-ab37290d-5af5-4882-9ed0-9cc19e5b3ce3.png">

**Comment by battosai30** [comment]
Ok the the error was a crash due to using old example syntax. So it's working :) great step !

I guess it's saturated (read the readme of the git).

Try something like : 

```
#include <MCP342x.h>
#include <Wire.h>

MCP342x MCP(0);

void setup() {

  Serial.begin(9600);  // start serial for output
  MCP.begin(0);
  MCP.setConfiguration(CH1,RESOLUTION_12_BITS,CONTINUOUS_MODE,PGA_X1); 

}

void loop(){

    Serial.print("Channel 1 : "); // print results
    Serial.print(MCP.measure());
    Serial.println(" microVolt");

    delay(500);

}
```

**Comment by niyuki** [comment]
But I want to get high resolution as possible shouldnt I try 18 bits then

**Comment by niyuki** [comment]
Results when I do 12bit: (at some time I just keep the wires from the battery away)
<img width="897" alt="image" src="https://user-images.githubusercontent.com/75905663/161985289-fb2360a8-0487-4334-83a5-0565244d56d7.png">
Are this values for a 1.5V battery realistic? Switching the poles at the battery made the values positive

**Comment by battosai30** [comment]
-1481 000 000 µV => -1.48V so, if you inverted polarity it's okay.

If you want 18 bits resolution, just change the setConfiguration() arguments

**Comment by niyuki** [comment]
Okay looks good when I do 18 bits but when I remove the wire form the battery it starts throwing random values it that normal? 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/75905663/162037444-94929e98-a914-48d2-94ec-a27daca1029c.png">

**Comment by battosai30** [comment]
What did you expected ?

**Comment by niyuki** [comment]
I mean when I try it with a new 1.5V battery it spits value over 1.68V

**Comment by battosai30** [comment]
But we agree it's not what your screenshot shows ?

**Comment by niyuki** [comment]
No, I used there an old battery. This is what I meant with over 1.58V but it should be 1.5V since it was never used or not?
<img width="937" alt="image" src="https://user-images.githubusercontent.com/75905663/162313851-5c70199a-2618-4117-9864-d9c4fefd583d.png">

**Comment by battosai30** [comment]
Battery voltages are just a mean value. It depends on its charge state. I'm not surprised at all by your values.

![image](https://user-images.githubusercontent.com/5184702/162393711-639a22a0-0c41-4187-b603-a0f879acf284.png)
